spring:
  config:
    import: "optional:file:./.env[.properties]"

  application:
    name: cruxmate

  datasource:
    url: jdbc:mysql://localhost:3306/cruxmate?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration


jwt:
  issuer: https://cruxmate.local
  secret: ${JWT_SECRET}
  access-token-expiration: 1h
