@baseUrl = http://localhost:8080

### 관리자 후보 회원 생성 (생성 직후 역할은 USER)
POST {{baseUrl}}/api/members
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "password123!"
}

### DB에서 ADMIN 승격 후 관리자 로그인
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "password123!"
}

### 일반 회원 생성
POST {{baseUrl}}/api/members
Content-Type: application/json

{
  "email": "member@example.com",
  "password": "password123!"
}

### 일반 회원 로그인
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "member@example.com",
  "password": "password123!"
}
