@baseUrl = http://localhost:8080
@memberId = 1
@sessionId = 1

### 세션 생성
POST {{baseUrl}}/api/sessions
Content-Type: application/json

{
  "title": "평일 저녁 중급 세션",
  "location": "광주 그랩잇",
  "startAt": "2026-08-02T19:00:00",
  "endAt": "2026-08-02T21:00:00",
  "reservationOpenAt": "2026-07-30T09:00:00",
  "reservationCloseAt": "2026-08-02T18:00:00",
  "capacity": 5,
  "level": "BEGINNER"
}

### 잘못된 세션 생성
POST {{baseUrl}}/api/sessions
Content-Type: application/json

{
  "title": "",
  "location": "",
  "capacity": 0
}

### 세션 조회
GET {{baseUrl}}/api/sessions/{{sessionId}}

### 세선 목록 조회
GET {{baseUrl}}/api/sessions?page=0&size=20